version: "3.9"
services:

  onboarding:
    container_name: onboarding
    working_dir: /
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - onboarding_volume:/onboarding_2021
    command: roscore
volumes:
  onboarding_volume:
